# Generated by Django 3.0.6 on 2020-05-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
                ('is_unsubscribed', models.BooleanField(default=False)),
            ],
        ),
    ]
